# Generated by Django 5.0.3 on 2025-04-07 06:48

import uuid

import django.db.models.deletion
from django.db import migrations, models

import project_characters.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(
                    blank=True, null=True,
                    upload_to=project_characters.models.character_image_path,
                    verbose_name='Image')),
                ('symbolism', models.TextField(blank=True, null=True, verbose_name='Symbolism')),
                ('character_arc', models.TextField(blank=True, null=True, verbose_name='Arc')),
                ('aliases',
                 models.JSONField(blank=True, default=list, null=True, verbose_name='Aliases')),
                ('role',
                 models.JSONField(blank=True, default=dict, null=True, verbose_name='Role')),
                ('demographics', models.JSONField(blank=True, default=dict, null=True,
                                                  verbose_name='Demographics')),
                ('appearance',
                 models.JSONField(blank=True, default=dict, null=True, verbose_name='appearance')),
                ('personality', models.JSONField(blank=True, default=dict, null=True,
                                                 verbose_name='Personality')),
                ('backstory',
                 models.JSONField(blank=True, default=dict, null=True, verbose_name='Backstory')),
                ('relationships', models.JSONField(blank=True, default=list, null=True,
                                                   verbose_name='Relationships')),
                ('additional_information', models.JSONField(
                    blank=True, default=dict, null=True,
                    verbose_name='Additional Information')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='characters', to='project.project')),
            ],
        ),
    ]
