# Generated by Django 5.0.3 on 2025-04-07 06:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('project_chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('characters',
                 models.JSONField(blank=True, default=list, null=True, verbose_name='Characters')),
                ('location',
                 models.JSONField(blank=True, default=dict, null=True, verbose_name='Location')),
                ('items',
                 models.JSONField(blank=True, default=list, null=True, verbose_name='Items')),
                ('time',
                 models.JSONField(blank=True, default=dict, null=True, verbose_name='Time')),
                ('weather',
                 models.JSONField(blank=True, default=dict, null=True, verbose_name='Weather')),
                ('goals',
                 models.JSONField(blank=True, default=list, null=True, verbose_name='Goals')),
                ('conflict',
                 models.JSONField(blank=True, default=dict, null=True, verbose_name='Conflict')),
                ('outcome',
                 models.JSONField(blank=True, default=dict, null=True, verbose_name='Outcome')),
                ('mood',
                 models.CharField(blank=True, max_length=100, null=True, verbose_name='Mood')),
                ('pov', models.CharField(blank=True, max_length=100, null=True,
                                         verbose_name='Point of View')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='scenes', to='project_chapters.page')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
