# Generated by Django 5.0.3 on 2025-04-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('project_scenes', '0002_alter_scene_mood_alter_scene_pov'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
    ]
