# Generated by Django 5.0.3 on 2025-04-22 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0004_project_chat_messages'),
        ('project_chapters', '0002_chapter_created_at_page_created_at'),
        ('project_scenes', '0003_scene_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='scenes', to='project_chapters.chapter'),
        ),
        migrations.AddField(
            model_name='scene',
            name='project',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='scenes', to='project.project'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='page',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='scenes', to='project_chapters.page'),
        ),
    ]
