# Generated by Django 5.0.3 on 2025-04-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('project_chapters', '0002_chapter_created_at_page_created_at'),
        ('project_scenes', '0004_scene_chapter_scene_project_alter_scene_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='scenes', to='project_chapters.chapter'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='page',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='scenes', to='project_chapters.page'),
        ),
    ]
