# Generated by Django 5.0.3 on 2025-04-07 06:48

import project.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Book name')),
                (
                    'file',
                    models.FileField(upload_to=project.models.book_path, verbose_name='Book')),
                ('pages',
                 models.JSONField(blank=True, default=dict, null=True, verbose_name='Book pages')),
                ('size', models.IntegerField(default=0, verbose_name='Book size')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True,
                                            upload_to=project.models.movie_image_path,
                                            verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('characters_json', models.JSONField(blank=True, default=list, null=True,
                                                     verbose_name='Characters JSON')),
            ],
        ),
    ]
