# Generated by Django 5.0.3 on 2025-04-07 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='projects', to=settings.AUTH_USER_MODEL,
                                    verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='book',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='book', to='project.project',
                                    verbose_name='Project'),
        ),
    ]
