# Generated by Django 5.0.3 on 2025-04-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chat',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Chat JSON'),
        ),
    ]
