# Generated by Django 5.0.3 on 2025-04-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0003_project_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chat_messages',
            field=models.JSONField(blank=True, default=list, null=True,
                                   verbose_name='Chat Messages JSON'),
        ),
    ]
