# Generated by Django 5.0.3 on 2025-04-07 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('process', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='processes', to='project.project',
                                    verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='subprocesses', to='process.process',
                                    verbose_name='Process'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='subprocess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='subprocesses', to='process.subprocess',
                                    verbose_name='Subprocess'),
        ),
    ]
