# Generated by Django 5.0.3 on 2025-04-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('process', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(default='in_progress', max_length=20, verbose_name='Status'),
        ),
    ]
