# Generated by Django 5.0.3 on 2025-04-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('process', '0003_alter_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='Description'),
        ),
    ]
