# Generated by Django 5.0.3 on 2025-04-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('process', '0004_process_description_subprocess_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True,
                                   verbose_name='Model name'),
        ),
        migrations.AddField(
            model_name='process',
            name='price_completion_tokens',
            field=models.FloatField(blank=True, default=0, null=True,
                                    verbose_name='Price completion tokens'),
        ),
        migrations.AddField(
            model_name='process',
            name='price_prompt_tokens',
            field=models.FloatField(blank=True, default=0, null=True,
                                    verbose_name='Price prompt tokens'),
        ),
        migrations.AddField(
            model_name='process',
            name='used_completion_tokens',
            field=models.IntegerField(blank=True, default=0, null=True,
                                      verbose_name='Used completion tokens'),
        ),
        migrations.AddField(
            model_name='process',
            name='used_prompt_tokens',
            field=models.IntegerField(blank=True, default=0, null=True,
                                      verbose_name='Used prompt tokens'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True,
                                   verbose_name='Model name'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='price_completion_tokens',
            field=models.FloatField(blank=True, default=0, null=True,
                                    verbose_name='Price completion tokens'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='price_prompt_tokens',
            field=models.FloatField(blank=True, default=0, null=True,
                                    verbose_name='Price prompt tokens'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='used_completion_tokens',
            field=models.IntegerField(blank=True, default=0, null=True,
                                      verbose_name='Used completion tokens'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='used_prompt_tokens',
            field=models.IntegerField(default=0, verbose_name='Used prompt tokens'),
        ),
        migrations.AlterField(
            model_name='subprocess',
            name='process',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='subprocesses', to='process.process',
                                    verbose_name='Process'),
        ),
        migrations.AlterField(
            model_name='subprocess',
            name='subprocess',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='subprocesses', to='process.subprocess',
                                    verbose_name='Subprocess'),
        ),
    ]
