# Generated by Django 5.0.3 on 2025-04-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('process', '0005_process_model_name_process_price_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprocess',
            name='status',
            field=models.CharField(default='in_progress', max_length=20, verbose_name='Status'),
        ),
    ]
