# Generated by Django 5.0.3 on 2025-04-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('process', '0006_alter_subprocess_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='type',
            field=models.CharField(blank=True, default='process', max_length=20, null=True,
                                   verbose_name='Type'),
        ),
    ]
