# Generated by Django 5.0.3 on 2025-04-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('process', '0007_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='subprocess',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_processes',
                                         to='process.process'),
        ),
    ]
