# Generated by Django 5.0.3 on 2025-04-15 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('process', '0008_process_subprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='subprocess',
        ),
        migrations.AddField(
            model_name='process',
            name='main_process',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='sub_processes', to='process.process'),
        ),
    ]
