# Generated by Django 5.0.3 on 2025-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('process', '0010_process_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='type',
            field=models.CharField(blank=True, default='process', max_length=80, null=True,
                                   verbose_name='Type'),
        ),
    ]
