# Generated by Django 5.0.3 on 2025-04-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_model',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
