# Generated by Django 5.0.3 on 2025-04-07 06:48

import uuid

import django.db.models.deletion
from django.db import migrations, models

import project_locations.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(blank=True,
                                            upload_to=project_locations.models.location_image_path,
                                            verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('symbolism', models.TextField(blank=True, verbose_name='Symbolism')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('geography_details',
                 models.JSONField(blank=True, default=dict, verbose_name='Geography')),
                ('culture_details',
                 models.JSONField(blank=True, default=dict, verbose_name='Culture')),
                ('historical_events',
                 models.JSONField(blank=True, default=list, verbose_name='Historical Events')),
                ('points_of_interest',
                 models.JSONField(blank=True, default=list, verbose_name='Points of Interest')),
                ('inhabitants_list',
                 models.JSONField(blank=True, default=list, verbose_name='Inhabitants')),
                ('atmosphere_details',
                 models.JSONField(blank=True, default=dict, verbose_name='Atmosphere')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='locations', to='project.project')),
            ],
        ),
    ]
