# Generated by Django 5.0.3 on 2025-04-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('format', models.TextField()),
            ],
        ),
    ]
