# Generated by Django 5.0.3 on 2025-04-07 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='chapters', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False)),
                ('text', models.TextField(default='', verbose_name='Text')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('characters',
                 models.JSONField(blank=True, default=list, verbose_name='Characters')),
                (
                    'locations',
                    models.JSONField(blank=True, default=list, verbose_name='Locations')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='Items')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='pages',
                                              to='project_chapters.chapter')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
