# Generated by Django 5.0.3 on 2025-04-07 06:48

import uuid

import django.db.models.deletion
from django.db import migrations, models

import project_items.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True,
                                            upload_to=project_items.models.image_image_path,
                                            verbose_name='Image')),
                ('category',
                 models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('description',
                 models.TextField(blank=True, null=True, verbose_name='Description')),
                ('symbolism', models.TextField(blank=True, null=True, verbose_name='Symbolism')),
                ('properties',
                 models.JSONField(blank=True, default=dict, verbose_name='Properties')),
                ('history', models.JSONField(blank=True, default=dict, verbose_name='History')),
                (
                    'abilities',
                    models.JSONField(blank=True, default=list, verbose_name='Abilities')),
                (
                    'ownership',
                    models.JSONField(blank=True, default=list, verbose_name='Ownership')),
                ('significance',
                 models.JSONField(blank=True, default=dict, verbose_name='Significance')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='items', to='project.project')),
            ],
        ),
    ]
